{% set name = "rosbags" %}
{% set version = "0.9.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rosbags-{{ version }}.tar.gz
  sha256: dc7fbaa41d61b2808e7e5798b491855229f117cb9ab0eaee8c8bb3ffa9889d0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - rosbags-convert = rosbags.convert.__main__:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - lz4
    - numpy
    - ruamel.yaml
    - zstandard

test:
  imports:
    - rosbags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/ternaris/rosbags
  summary: Pure Python library to read, modify, convert, and write rosbag files.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - durko
