{% set name = "rosbags" %}
{% set version = "0.9.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rosbags-{{ version }}.tar.gz
  sha256: 3cabd531b01cdae58c953b855d15c29b1d1040d27bbb69f9b443498839677e14

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - rosbags-convert = rosbags.convert.__main__:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - lz4
    - numpy
    - ruamel.yaml
    - zstandard

test:
  imports:
    - rosbags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/ternaris/rosbags
  summary: Pure Python library to read, modify, convert, and write rosbag files.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - durko
