{% set name = "rosbags" %}
{% set version = "0.9.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rosbags-{{ version }}.tar.gz
  sha256: a3e6bed79d8ee49d0e2bf998df016d4c1e2a36e0910753b5c39fe3a5b652efa0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - rosbags-convert = rosbags.convert.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - lz4
    - numpy
    - ruamel.yaml
    - zstandard

test:
  imports:
    - rosbags
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/ternaris/rosbags
  summary: Pure Python library to read, modify, convert, and write rosbag files.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - durko
